In [1]:
#1. 导入numpy库并简写为 np (★☆☆)
import numpy as np

In [21]:
#2. 打印numpy的版本和配置说明 (★☆☆)
print(np.__version__)
print('-'*30)
# np.show_config()

1.17.0
------------------------------


In [6]:
#3. 创建一个长度为10的空向量 (★☆☆)
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# 4. 如何找到任何一个数组的内存大小？ (★☆☆)
a= np.zeros((10,10))
print("内存大小为 {} bytes".format(a.size*a.itemsize))
print("%d bytes" % (a.size * a.itemsize))

内存大小为 800 bytes
800 bytes


In [22]:
# 5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)
# np.info(np.add)
# np.add?

In [17]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)
b = np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [19]:
# 7. 创建一个值域范围从10到49的向量(★☆☆)
c = np.arange(10,50) # 前包后不包
# c

In [23]:
# 8. 反转一个向量(第一个元素变为最后一个) (★☆☆)
b[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [25]:
# 9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)
index = np.nonzero([1,2,0,0,4,0])
index

(array([0, 1, 4], dtype=int64),)

In [30]:
#11. 创建一个 3x3 的单位矩阵 (★☆☆)
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# 12. 创建一个 3x3x3的随机数组 (★☆☆)
b = np.random.random((3,3,3))
b

array([[[0.3562712 , 0.5702186 , 0.87582419],
        [0.88877604, 0.89732425, 0.33781172],
        [0.50106143, 0.674767  , 0.162062  ]],

       [[0.95245908, 0.08695704, 0.18337585],
        [0.05788312, 0.4299224 , 0.55066227],
        [0.59051848, 0.80404319, 0.70905006]],

       [[0.31547482, 0.20032693, 0.27223654],
        [0.60521788, 0.77739251, 0.18103114],
        [0.39715586, 0.31776822, 0.65223273]]])

In [35]:
c = np.random.random((10,10))
c.min()
c.max()

0.9935503583373713

In [36]:
# 14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)¶
d= np.random.random(30)
d.mean()

0.4882691760230426

In [39]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
# 17. 以下表达式运行的结果分别是什么? (★☆☆)
#提示: NaN = not a number, inf = infinity)
print(1,0*np.nan)
print(2,np.nan==np.nan)
print(3,np.inf>np.nan)
print(4,np.nan-np.nan)
print(5,np.nan is np.nan)
print(6,0.3 ==3*0.1)  
print(3*0.1)
print(4.1-0.2==3.9) # False
print(4.1-0.2)
print(4-0.1==3.9)  # True  # 小数之间相减得到的结果是不可预订的


1 nan
2 False
3 False
4 nan
5 True
6 False
0.30000000000000004
False
3.8999999999999995
True


In [7]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
a = np.diag(1 + np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [14]:
#19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [15]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [43]:
#21. 用tile函数去创建一个 8x8的棋盘样式矩阵
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
a
# 解法2
b = np.zeros((8,8),dtype = int)
b[1::2,::2]=1
b[::2,1::2]=1
b

In [55]:
# 22. 对一个5x5的随机矩阵做归一化(★☆☆)
a = np.random.random((5,5))
amax,amin = a.max(),a.min()
b= (a-amin)/(amax-amin)
b

array([[0.41197145, 0.3523567 , 1.        , 0.2660228 , 0.90676491],
       [0.87366472, 0.57918538, 0.33962766, 0.71143837, 0.24281446],
       [0.16336073, 0.18367629, 0.87367041, 0.84233252, 0.63718674],
       [0.        , 0.17987138, 0.28591776, 0.34760512, 0.11072929],
       [0.81966289, 0.32220793, 0.60924991, 0.75325208, 0.60603441]])

In [60]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)
color = np.dtype([("r",np.ubyte,1),
                  ("g",np.ubyte,1),
                  ("b",np.ubyte,1),
                  ("a",np.ubyte,1)])
color

d:\miniconda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [71]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)
a = np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [80]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)
a = np.arange(11)

b = a[(a>3)& (a<=8)]
b

array([4, 5, 6, 7, 8])

In [1]:
# 26. 下面脚本运行后的结果是什么? (★☆☆)
print(sum(range(5),10))
# sum 函数存在起始值
import numpy as np 
print(np.sum(range(5),-1)) 
print(np.sum(range(5),axis=-1)) 
print(np.sum(range(5),axis=0)) # 相当于按行求和.按列对列的每一行进行计算

20
10
10
10


In [16]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)
a = np.array([1,2,3])


In [20]:
print(a*a) # 对应平方
print(a**a) # 对应为求次方

[1 4 9]
[ 1  4 27]


In [31]:
a = np.array([1,-2,3])
# 2<<a >> 2 # 移位运算
# a <- a # 先给a取反然后对应比较大小
# 1j*a #  复数运算
# a/1/1
# a<a>a false

In [34]:
# 28. 下列表达式的结果分别是什么?(★☆☆)
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [36]:
# 29. 如何从零位对浮点数组做舍入 ? (★☆☆)
# np.uniform, np.copysign, np.ceil, np.abs
Z = np.random.uniform(-10,+10,10)
Z
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-4.  1.  1. -3.  4.  1. -7. -5.  3.  9.]


In [45]:
# 30. 如何找到两个数组中的共同元素? (★☆☆)
a = np.random.randint(0,10,10) # 0-9 随机整数,10 个数,在python 中只能一次取一个数
b = np.random.randint(0,10,10)
c = np.intersect1d(a,b)
c

array([1, 5, 8])

In [48]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# # An equivalent way, with a context manager:

with np.errstate(divide='ignore'): # 上下文管理
    
    Z = np.ones(1) / 0

d:\miniconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [ ]:
# 32. 下面的表达式是正确的吗? (★☆☆)

In [58]:
# np.sqrt(-1) == np.emath.sqrt(-1) # 前者返回一个NaN的数,但是后者返回的是一个复数,
#所以 2者之间不等.
# np.sqrt(4) == np.emath.sqrt(4)
np.emath.sqrt(-1)#1j

1j

In [62]:
# 33. 如何得到昨天，今天，明天的日期? (★☆☆)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


In [66]:

print(np.datetime64('now'))

2019-08-07T13:00:09


In [69]:
# 34. 如何得到所有与2016年7月对应的日期？ (★★☆)
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))  # 得到某范围内的日期

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [71]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (
a = np.ones(3)*1
b = np.ones(3)*2
c = np.ones(3)*3
np.add(a,b,out=b)

array([3., 3., 3.])

In [72]:
 np.divide(a,2,out=a)

array([0.5, 0.5, 0.5])

In [73]:
np.negative(a,out=a)

array([-0.5, -0.5, -0.5])

In [75]:
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

In [79]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆
A= np.random.uniform(0,10,10)
A
print (Z - Z%1)

[0. 1. 7. 5. 4. 8. 4. 7. 4. 3.]


In [80]:
print(np.floor(A))

[5. 0. 2. 2. 8. 2. 1. 2. 4. 1.]


In [88]:
print(np.ceil(A)-1)

[5. 0. 2. 2. 8. 2. 1. 2. 4. 1.]


In [82]:
print(A.astype(int))

[5 0 2 2 8 2 1 2 4 1]


In [89]:
print (np.trunc(A))

[5. 0. 2. 2. 8. 2. 1. 2. 4. 1.]


In [93]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
a = np.zeros((5,5))
a+=np.arange(5)


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [121]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组
# 方法一:推荐使用
def func1():
    yield from range(10)
# a = np.fromiter(func1(),dtype=float,count=-1)
# print (a)
# 方法2
def func1():
    for x in range(10):
        yield x
a = np.fromiter(func1(),dtype=float,count=-1)


In [133]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)
# (提示: np.linspace)
a = np.linspace(0,1,11,endpoint= False)[1:]
a
# b = np.random.uniform(0,1,10)


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [145]:
# 40. 创建一个长度为10的随机向量，并将其排序 (★★☆)
a = np.random.random(10)
a.sort()

a

array([0.15122412, 0.20968607, 0.41857668, 0.4697607 , 0.58839722,
       0.65483143, 0.76457165, 0.82155706, 0.89466474, 0.92119099])

In [148]:
# 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)
a = np.arange(10)
np.add.reduce(a)


45

In [154]:
# 42. 对于两个随机数组A和B，检查它们是否相等(★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)
A = np.ones((2,3))
B = np.ones((2,3))
print(np.allclose(A,B))
print(A is B)
print(A ==B)
# 方法二:
equal = np.array_equal(A,B)
print(equal)

False
True
False
[[ True  True  True]
 [ True  True  True]]
True


In [161]:
# 43. 创建一个只读数组(read-only) (★★☆)
a = np.zeros(10)
print(a)
a.flags.writeable = False
# a[0]=1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [162]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.60789292 0.73141727 0.38234849 0.87157489 0.79321018 1.01772654
 0.20980192 0.78944307 1.07091841 1.10229975]
[0.48032326 1.29033053 1.22257455 0.34439002 0.65626578 0.21996938
 0.05689276 0.05301114 1.05682949 0.95028065]


In [169]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1
a = np.random.random(10)
# print(a)
a[a.argmax()]=1
print(a)
# print(a.max()) a.max()只能返回当前数组的最大值,但是并不能赋值,所以不行
# a.max()=10
# print(a)

[1.         0.7328469  0.72055444 0.44116311 0.94656617 0.23866429
 0.69075313 0.77334339 0.28047473 0.52637991]


In [170]:
# 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)
# (提示: np.meshgrid)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [173]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
# print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


In [174]:
# 48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)
# (提示: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [180]:
# 49. 如何打印一个数组中的所有数值? (★★☆)
# np.set_printoptions(threshold=np.nan)
# Z = np.zeros((16,16))
# print (Z)
# 有问题

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [181]:
# 50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print (a[index])

23


In [189]:
# 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组(★★☆)
# (提示: dtype)
import sys
a = np.zeros(10, [ ('position', [ ("x", float, (1,)),
                                  ("y", float, (1,))]),
                   ('color',    [ ("r", float, (1,)),
                                  ("g", float, (1,)),
                                  ("b", float, (1,))])])
# print (a)